Importing

In [73]:
import numpy as np
import tensorflow as tf

Creating the samples

In [76]:
X_train = np.random.randint(0, 90, (100000, 1))
y_train = X_train.flatten()

X_test = np.random.randint(0, 90, (100000, 1))
y_test = X_test.flatten()

print(X_train, y_train)

[[13]
 [84]
 [41]
 ...
 [73]
 [ 2]
 [55]] [13 84 41 ... 73  2 55]


Creating the model

In [77]:
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(1, 1)),
                                    tf.keras.layers.Dense(1024, activation='sigmoid'),
                                    tf.keras.layers.Dense(512, activation='sigmoid'),
                                    tf.keras.layers.Dense(256, activation='sigmoid'),
                                    tf.keras.layers.Dense(128, activation='sigmoid'),
                                    tf.keras.layers.Dense(91, activation=tf.nn.softmax)])
model.compile(optimizer=tf.optimizers.Adam(),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10)

print(model.evaluate(X_test, y_test))

Epoch 1/10
3125/3125 [==============================] - 40s 12ms/step - loss: 2.1669 - accuracy: 0.3488
Epoch 2/10
3125/3125 [==============================] - 39s 13ms/step - loss: 0.9778 - accuracy: 0.7330
Epoch 3/10
3125/3125 [==============================] - 38s 12ms/step - loss: 0.6108 - accuracy: 0.8501
Epoch 4/10
3125/3125 [==============================] - 38s 12ms/step - loss: 0.4518 - accuracy: 0.8939
Epoch 5/10
3125/3125 [==============================] - 38s 12ms/step - loss: 0.3781 - accuracy: 0.9161
Epoch 6/10
3125/3125 [==============================] - 38s 12ms/step - loss: 0.3289 - accuracy: 0.9363
Epoch 7/10
3125/3125 [==============================] - 38s 12ms/step - loss: 0.3111 - accuracy: 0.9290
Epoch 8/10
3125/3125 [==============================] - 38s 12ms/step - loss: 0.3134 - accuracy: 0.9252
Epoch 9/10
3125/3125 [==============================] - 38s 12ms/step - loss: 0.2780 - accuracy: 0.9410
Epoch 10/10
3125/3125 [==============================] - 22s 7ms

Predictions

In [78]:
y_predicted = model.predict(X_test)
for i in range(len(y_predicted)):
    y_predicted[i]=np.argmax(y_predicted[i])
print(X_test, 'Y predicted', y_predicted)


3125/3125 [==============================] - 20s 6ms/step
[[21]
 [33]
 [39]
 ...
 [64]
 [70]
 [ 8]] Y predicted [[21. 21. 21. ... 21. 21. 21.]
 [33. 33. 33. ... 33. 33. 33.]
 [39. 39. 39. ... 39. 39. 39.]
 ...
 [64. 64. 64. ... 64. 64. 64.]
 [70. 70. 70. ... 70. 70. 70.]
 [ 8.  8.  8. ...  8.  8.  8.]]


Accuracy

In [80]:
# accuracy_score(y_test, y_predicted)

print(y_test, np.argmax(y_predicted[0]))

[21 33 39 ... 64 70  8] 0


User

In [94]:
user_age = int(input("Enter your age: "))

y_user_predicted = model.predict([user_age])

print(user_age, np.argmax(y_user_predicted[0]))


1/1 [==============================] - 0s 48ms/step
49 49
